#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/3455ee87-b368-432c-a071-e8fb4b7339a9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String messg;
  bool dETECTOR_STATUS;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "ESP32Servo.h"
const int ledPin=2;
const int pirPin=27;
const int servoPin=5;
Servo servo;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  servo.attach(servoPin,500,2400);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
 
  pinMode(ledPin,OUTPUT);
  pinMode(pirPin,INPUT);
  // Defined in thingProperties.h
  Serial.println("I am Waiting.....");
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}
int pos=0;
void loop() {
  ArduinoCloud.update();
  // Your code here 
  int reading = digitalRead(pirPin);
  dETECTOR_STATUS=reading;
  if(reading==HIGH){
    Serial.println("Motion Detected");
    digitalWrite(ledPin,HIGH);
    for (pos = 0; pos <= 180; pos += 1) {
    servo.write(pos);
    delay(15);
  }
    messg="Motion Detected";
  }else{
    Serial.println("No Motion Dectected");
    digitalWrite(ledPin,LOW);
    messg="Motion NOT Detected";
  //  SRB=0;
  }
  delay(2000);

  
}



/*
  Since DETECTORSTATUS is READ_WRITE variable, onDETECTORSTATUSChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDETECTORSTATUSChange()  {
  // Add your code here to act upon DETECTORSTATUS change
}

/*
  Since Messg is READ_WRITE variable, onMessgChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMessgChange()  {
  // Add your code here to act upon Messg change
}