// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "4f6a5d6b-97ee-4bf9-ba5d-41783c9226c8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMessgChange();
void onDETECTORSTATUSChange();

String messg;
bool dETECTOR_STATUS;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(messg, READWRITE, ON_CHANGE, onMessgChange);
  ArduinoCloud.addProperty(dETECTOR_STATUS, READWRITE, ON_CHANGE, onDETECTORSTATUSChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
